### ISSUE TITLE
Wall Collision

### ISSUE THREAD

**Issue by HiNett** [algosup/2023-2024-project-2-x86-retrogaming-team-7#27]
#### Encountered error - General definition:
- Pac-Man can pass through walls at certain times.

#### Detailed error:
- The last pixel of the first line only (based on the right side) is used as a controller to check the color of the pixel in front to see if the color is equal to 0x37 (wall color).

#### What the program should have done:
- Pac-Man should have had the last complete column as a controller to check the color of the pixels in front.

**Comment by Ianlaur** [comment]
Still some issues, Pac-man can eat the Maze in the corners of the walls minor Bug but has to be fixed.
![menu_007](https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-7/assets/146005340/5b3bb599-b0bd-401d-87bd-c45756b4123f)

**Comment by Ianlaur** [comment]
No more wall collision issue however, one last issue: Pac-Man movements are restricted in the Maze to change direction if Pac-Man is not in the right pixel line, it will find himself stuck and unable to move.

![menu_013](https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-7/assets/146005340/73b11cec-0d26-470e-a926-5bf85784cc8d)

**Comment by HiNett** [comment]
Wall Collision Issue Fixed in [625f161](https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-7/commit/625f1616f11d152273aa6077ef065c9e77624f30).
