### ISSUE TITLE
Pac-Man teleportation

### ISSUE THREAD

**Issue by HiNett** [algosup/2023-2024-project-2-x86-retrogaming-team-7#28]
The tunnel is not transmitted.
The Pac-Man passes through the map, and can therefore erase the contents of the map. 

The error appeared in the update: [a98dab4](https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-7/commit/a98dab4d0e517ee532be01398350a8bb673d88b9)

**Comment by Ianlaur** [comment]
Everything looks good now!

**Comment by HiNett** [comment]
Fixed in [4182863](https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-7/commit/41828630bff4b62ddd5ab14609011569eb9ce5cb) !
