### ISSUE TITLE
Ghosts eating maze

### ISSUE THREAD

**Issue by Ianlaur** [algosup/2023-2024-project-2-x86-retrogaming-team-7#30]
Ghosts eat the Maze and don't stay in Maze.
![menu_005](https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-7/assets/146005340/76688b5a-78b2-43c3-839a-9ff7c9e021c2)

**Comment by GuillaumeDespaux** [comment]
Good now ghosts have collisions too

**Comment by Ianlaur** [comment]
Just saw the changes, not quite that ghosts can still eat the Maze in some corners....

**Comment by HiNett** [comment]
Fixed in commit [625f161](https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-7/commit/625f1616f11d152273aa6077ef065c9e77624f30).
