### ISSUE TITLE
Blinky Flickering 

### ISSUE THREAD

**Issue by Ianlaur** [algosup/2023-2024-project-2-x86-retrogaming-team-7#31]
Blinky is flickering clear sprite? Or Print?
![menu_006](https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-7/assets/146005340/7cb3a072-4ca5-4df1-aa72-c077eea1aaac)

**Comment by HiNett** [comment]
The problem is fixed in : [0486704](https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-7/commit/04867045b1a15d6676824acb7b1b608f23e05b84)
