### ISSUE TITLE
Pellets

### ISSUE THREAD

**Issue by Ianlaur** [algosup/2023-2024-project-2-x86-retrogaming-team-7#33]
Every pellet gives 20 points instead of 10 points, The problem with the pellets is that Pac-Man eats just half of it giving out 10 points meaning that every time Pac-man eats the whole pellet as it is 2 pixel large there is an issue.

![menu_012](https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-7/assets/146005340/016eb6c1-d720-43e4-913c-62ba2c13ffb6)

**Comment by HiNett** [comment]
Fixed in [bd7d923](https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-7/commit/bd7d923dcca9c4ac66784c8d2a6da94f5de40615) !
