### ISSUE TITLE
Super pellets

### ISSUE THREAD

**Issue by Ianlaur** [algosup/2023-2024-project-2-x86-retrogaming-team-7#34]
Super pellets are not functional, don't give the points nor put the ghosts in a vulnerable state.

**Comment by HiNett** [comment]
Update : From now on, Super Pellets give the right number of points. However, ghosts still need to be transformed into vulnerable ones.

**Comment by HiNett** [comment]
Super Pellets are now implemented in the map reset.
Fixed in : [f3f813a](https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-7/commit/f3f813aeb5c03a1b350ae8ded4f55593203e4b60)

Vulnerable phantoms have still not been implemented.

**Comment by Ianlaur** [comment]
thanks!
