### ISSUE TITLE
End game

### ISSUE THREAD

**Issue by Ianlaur** [algosup/2023-2024-project-2-x86-retrogaming-team-7#35]
When all pellets are eaten the game doesn't end

**Comment by HiNett** [comment]
Same as issue #36.
We need context, and also saying "End game" as a title doesn't help us find and indicate when the errors are over.
"When all pellets are eaten the game doesn't end", what exactly is going on? How did you make this happen? Can you quote the last commit you have to tell me when this problem started?

**Comment by Ianlaur** [comment]
Hi sorry for the confusion here is a the issue more precisely since the last commit "ff4c064" :
the last commit that was done corrected the initial issue however due to the ghosts eating the pellets Pac-man doesn't eat all the pellets.

**Comment by Ianlaur** [comment]
Fixed thanks!
