### ISSUE TITLE
Ghosts

### ISSUE THREAD

**Issue by Ianlaur** [algosup/2023-2024-project-2-x86-retrogaming-team-7#36]
Ghosts aren't moving.

**Comment by HiNett** [comment]
I'm going to ask you to be a little more specific in your remarks.
It's hard to know what the overall problem is with the title of the issue, plus the "Ghosts aren't moving" explanation, a little more precision is required on "How did the problem arise?", "What's happening?", "What should have happened?", etc....

**Comment by Ianlaur** [comment]
Hi I'm sorry for the confusion, here is a more specified comment about the issue : 
The ghost animations of the sprites are working however when the game is launched the ghost movements on the map are not working they are all stuck in one corner. 
Here is a picture for some visual on the is
![Screenshot 2023-12-21 at 13 51 13](https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-7/assets/146005340/0b2509f0-a3f5-4850-92dc-ce484f2f7c31)
sue :

**Comment by HiNett** [comment]
Fixed in : [3d78b9b](https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-7/commit/3d78b9b04bf89f5df7c42d06db7a59cb4401b370) !
