### ISSUE TITLE
Functional specification

### ISSUE THREAD

**Issue by Ianlaur** [algosup/2023-2024-project-2-x86-retrogaming-team-7#4]
## Project overview : 

- This project started on Monday November 6th and its deadline is on Thursday December 21st. (Syntax error) --> This project debuted on Monday the 6th of November, and its deadline is Thursday the 21st  of December 2023. 

## Game description : 

- So what is Pac-Man? (Familiar language)--> Pac-man overview. (more formal)
- Pac-Man is a maze-based and a single player video game set in a brightly colored, released in 1980 in Japan. The player takes control of a yellow character, known as Pac-Man. The objective of the game is to clear all the dots from the maze while avoiding four colorful ghosts who are out to catch Pac-Man. The player earns points by consuming dots and, occasionally, larger dots, which temporarily turn the ghosts vulnerable, then Pac-Man can eat them to earn more points. The player can play until he loses all his lives. (replace with)
--> Pac-Man is a game created in 1980 in Japan, it's a single-player video game where the player takes control of a yellow character also known as Pac-Man, to which the player's goal will be to collect all the points represented as dots in a Maze. This yellow character is followed by ghosts whose main goal is to catch Pac-man. If Pac-Man gets caught by a ghost the game pauses and both Pac-Man and the ghosts return to their initial starting points. Pac-man has three lives and if he loses all three lives the game ends and the points are lost. In the Game there are some features such as "super points" which are distinguished on the map with a larger dot,  this points will allow Pac-Man to be the one chasing the ghosts and allow him to win more points if he manages to catch one or more. (More clear + add explanation of what the fruits do in the game) 

## Project goals : 
- To add boss stages (in non-goals replace with) --> Implementing levels with a "Boss" for a more challenging level

### Description
- For this project we were asked to use the software DOSBox [4] which is a simulator of a MS-DOS environment.As well as DOSBox, NASM [5]  will also be required for the project (Add and replace) --> For this project we were asked to use the software DOSBOX [4]  which is a simulator of **the** MS-DOS environment. In addition to DOSbox, NASM [5] was part of the initial requirement. 

### Acceptance Criteria
- Each system will have to use this software to launch the final product. (Ambiguous) --> The final product must run on this software in order for it to be valid. 
- The DOSBox emulator will be integrated into an installer, which will be supplied when the final product will be launched. (tense) --> The DOSbox emulator will have to integrated into an installer which will ease the download of the final product.

### Acceptance Criteria
- The game must be complete with no issues, crashs, bugs or glitchs during all the user's experience. (Grammatical errors) --> The final product must not have any issues, crashes, **system failures**, or glitches throughout the whole user's experience.

### 2.4 "control" menu as the settings --> Settings in menu
- The settings will be accessible from the main menu, it will allows to customise the player's key binds. --> The settings will be accessible from the main menu, which will allow the user to customize the  key binds.

### 2.6 Map
When the player starts the game, it will take place in a map. The whole map deals with all the maze, and it will all be displayed on the screen. (change the phrase, not comprehensible) 

### 2.7 Pac-Man
- The famous character Pac-Man is the playable one in the game. The player who controls him can change his direction, while he's moving, in 4 directions (up, left, right and down), he also can eat dots by just going on them. --> The player will have the possibility to control the movements of the yellow character known as Pac-Man in the maze, the player will have control over the 4 directions (up, down, left, and right). 

### 2.9 Enemies 
Precise the names of the ghosts and add them to the sprites.

### 2.11 Score --> Scoring 
- The score shows the points the player earned during the game. The little dots earn 10 points, the power pellets earn 30 points when the player eats a vulnerable ghost (until 1600 points, depending on the consecutive ghost eats), he earns 200 points; and a bonus earns from 100 points to 5000. A highscore can be displayed on the screen, the player could want to beat it. (unclear and makes sure that the high score stays the same every time we relaunch the game) --> The score is displayed on the screen, for each dot that Pac-Man eats, the player's score will increase by 10 points, for each power pellet the player will increase its score by 30 points. As for the ghosts, every time a player eats a power pellet and catches a ghost, the player's score will increase by 200, depending on the number of ghosts the player catches in their vulnerable state. Every ghost that will be caught, will allow the player to gain more points every time. The highest score of the previous games will be displayed next to the game score which will allow the player to see its progression from the previous games. 

### 2.12 Bonus 
- In Pac-Man, the bonus are the objects which appear on the map, they just earn points. --> In Pac-Man, the bonus is the objects that appear on the map, which they allow to earn points every time Pac-Man eats it. (Fruit?)

### 2.13 Lives
The lives are the chances the player has to beat the game. If he has no lives anymore, it's game over. If the player earns 10,000 points, he gets another life. (Syntax and Grammer) 
--> The lives are the chances that the player has to complete the game, when the player launches the game he will initially have 3 lives, everytime that Pac-Man gets caught by a ghost he loses one life and returns to the original position keeping he's score and the progression on the map. Everytime the player reaches 10 thousand points the player will be rewarded with an extra life. If the player runs out of lives the game will be over and he will have to start the game over.

### Sprites
- mention names of the ghosts
- Mention the difference in the picture of the points and power pellets. 
- High-score --> High-scores (not matching to what was said in the scoring part 2.11 **find solution**)

This is how the game would look like: --> Here is a general idea of what the final product will look like: (because our game won't exactly look alike to what is shown in the photo)

### Game mode --> Game modes
- Multiplayer game mode:
This game mode is based on **a** two player **version**, **The first player will be able to** control Pac-Man ~~with the original objective~~, the other player **will have the possibility** ~~takes~~ **to take** control of one of the ghosts ~~and has the objective~~ **this players goal will be to catch with the three other ghosts, Pac-Man whom is controled by the first player.** ~~to catch the other player accompanied with the other ghosts~~. Both players ~~control~~ **will have control of** their character**s** with the same keyboard **with different control keys**

- Reverse game mode:
In this game mode, the player takes control of the red ghost ~~and has the objective to catch~~ **with the goal of catching**  Pac-Man ~~accompanied with the three other ghosts~~ **with the three other ghosts**. Pac-Man ~~has~~ **will have** three lives ~~as~~ **just like** the original game and it ~~has~~ **will have** its own pattern. The player ~~wins~~ **will win** if Pac-Man has no lives left but he loses if it eats all the dots.

- Time game mode:
This game mode is like the original ~~one~~ **version** but with a limited time ~~determined which is reduced further the player wins level.~~ **, this time limit will decrease as the player goes up a level.**

### Settings in game --> Game settings
- Music : Give the possibility to put on/off the music of the game. --> Possibility of switching on/off the music of the game
- Sound effect : Give the possibility to put on/off the sound effect of the game. --> Possibility of switching on/off the sound effects of the game.
- Character : ~~Give the~~ **P**ossibility to select one of the available skin**s** ~~implemented~~ **available** in the game.
- Keybind : ~~Give the~~ **P**ossibility to configure the keybinds as the player want. 

- - Default ~~key binds~~ **keybinds** for the first player moves :
- - Default ~~key binds~~ **keybinds** for the second player moves **(AZERTY keyboard)** : 

### Design
Here's a description of what the game would look like in the player's sight. --> Here is the UML case diagram from the users' point of view, grouping the basic functionalities of the supposedly final product.

### Assumptions
The game will be available to download on (...) and once the game installed, the game will be able to run without the need to be connected to the internet.

## Risks
- Not deliver the final product on time. --. Not being able to deliver the final product on due date.
- Make the game not working/launching on the customer's hardware. --> The final product not working on the customer's device.
- To not credit regarding the copyrights. (Maybe not necessary to mention)
- (adding) The game interactions such as game control or opening menu not functioning.
- (adding) Going over the limit of 16 bits.
- (adding) Customer not satisfied with the final product.

**Comment by GuillaumeDespaux** [comment]
As requested there is a commit with all changes required, I also add a new folder that contains all images needed for the functional.
https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-7/commit/a2027e68ad957ae5f1322ccb1ac590b5371a01cd

**Comment by GuillaumeDespaux** [comment]
Functional documentation merge on main -> close
